package GUI;

import advertisement.abstracts.House;
import advertisement.concretes.Advertisement;
import advertisement.concretes.HouseFactory;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import user.concretes.HouseOwner;

public class AdvertisementUpdateScreen extends javax.swing.JFrame {

    File[] files = new File[6];
    String[] paths = new String[6];
    String[] fileNames = new String[6];
    int s = 0;

    private ImageIcon format = null;
    byte[] pimage = null;

    Connection db = Singleton.SingletonConnection.getCon();
    PreparedStatement pst;
    ResultSet rs;
    HouseOwner houseOwner;
    Advertisement advertisement;

    public AdvertisementUpdateScreen() {
    }

    public AdvertisementUpdateScreen(HouseOwner houseOwner, Advertisement advertisement) {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        this.houseOwner = houseOwner;
        this.advertisement = advertisement;
        advertisementName.setText(advertisement.getAdvertisementName());
        roomNumber.setSelectedItem(advertisement.getHouse().getRoomNumber());
        heatingType.setSelectedItem(advertisement.getHouse().getHeating());
        advertisementType.setSelectedItem(advertisement.getAdvertisementType());

        if (advertisement.getHouse().isHasVehiclePark() == true) {
            yesPark.setSelected(true);
            noPark.setSelected(false);
        } else {
            yesPark.setSelected(false);
            noPark.setSelected(true);
        }
        address.setText(advertisement.getHouse().getLocation());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hasPark = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        advertisementName = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        heatingType = new javax.swing.JComboBox<>();
        roomNumber = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yesPark = new javax.swing.JRadioButton();
        noPark = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        advertisementType = new javax.swing.JComboBox<>();
        dailyPrice = new javax.swing.JFormattedTextField();
        image4 = new javax.swing.JButton();
        image2 = new javax.swing.JButton();
        image3 = new javax.swing.JButton();
        image1 = new javax.swing.JButton();
        image5 = new javax.swing.JButton();
        image6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shortDescription = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        turnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1380, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1380, 800));

        jPanel2.setBackground(new java.awt.Color(255, 90, 95));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1330, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        add.setBackground(new java.awt.Color(204, 204, 204));
        add.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        add.setText("UPDATE");
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        advertisementName.setEditable(false);
        advertisementName.setBackground(new java.awt.Color(51, 51, 51));
        advertisementName.setForeground(new java.awt.Color(255, 255, 255));
        advertisementName.setToolTipText("");
        advertisementName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADVERTISEMENT NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        advertisementName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertisementNameActionPerformed(evt);
            }
        });

        address.setEditable(false);
        address.setBackground(new java.awt.Color(51, 51, 51));
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        address.setToolTipText("");
        address.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADDRESS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        heatingType.setBackground(new java.awt.Color(204, 204, 204));
        heatingType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        heatingType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combi Boiler", "Wood", "Numerator" }));
        heatingType.setEnabled(false);
        heatingType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heatingTypeActionPerformed(evt);
            }
        });

        roomNumber.setBackground(new java.awt.Color(204, 204, 204));
        roomNumber.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        roomNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1+1", "2+1", "3+1", "4+1", "5+2" }));
        roomNumber.setEnabled(false);
        roomNumber.setFocusable(false);
        roomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNumberActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HEATING");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ROOM NUMBER");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HAS VEHICLE PARK");

        yesPark.setBackground(new java.awt.Color(51, 51, 51));
        hasPark.add(yesPark);
        yesPark.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        yesPark.setForeground(new java.awt.Color(255, 255, 255));
        yesPark.setSelected(true);
        yesPark.setText("YES");
        yesPark.setEnabled(false);

        noPark.setBackground(new java.awt.Color(51, 51, 51));
        hasPark.add(noPark);
        noPark.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        noPark.setForeground(new java.awt.Color(255, 255, 255));
        noPark.setText("NO");
        noPark.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HOUSE TYPE");

        advertisementType.setBackground(new java.awt.Color(204, 204, 204));
        advertisementType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        advertisementType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartment", "Manor", "Tree House", "Villa" }));
        advertisementType.setEnabled(false);
        advertisementType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advertisementTypeActionPerformed(evt);
            }
        });

        dailyPrice.setBackground(new java.awt.Color(51, 51, 51));
        dailyPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DAILY PRICE *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        dailyPrice.setForeground(new java.awt.Color(255, 255, 255));
        try {
            dailyPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dailyPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dailyPrice.setToolTipText("");
        dailyPrice.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        dailyPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyPriceActionPerformed(evt);
            }
        });

        image4.setBackground(new java.awt.Color(51, 51, 51));
        image4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        image4.setForeground(new java.awt.Color(255, 255, 255));
        image4.setText("IMAGE 4 *");
        image4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image4ActionPerformed(evt);
            }
        });

        image2.setBackground(new java.awt.Color(51, 51, 51));
        image2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        image2.setForeground(new java.awt.Color(255, 255, 255));
        image2.setText("IMAGE 2 *");
        image2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image2ActionPerformed(evt);
            }
        });

        image3.setBackground(new java.awt.Color(51, 51, 51));
        image3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        image3.setForeground(new java.awt.Color(255, 255, 255));
        image3.setText("IMAGE 3 *");
        image3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image3ActionPerformed(evt);
            }
        });

        image1.setBackground(new java.awt.Color(51, 51, 51));
        image1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        image1.setForeground(new java.awt.Color(255, 255, 255));
        image1.setText("IMAGE1 *");
        image1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image1ActionPerformed(evt);
            }
        });

        image5.setBackground(new java.awt.Color(51, 51, 51));
        image5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        image5.setForeground(new java.awt.Color(255, 255, 255));
        image5.setText("IMAGE 5 *");
        image5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image5ActionPerformed(evt);
            }
        });

        image6.setBackground(new java.awt.Color(51, 51, 51));
        image6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        image6.setForeground(new java.awt.Color(255, 255, 255));
        image6.setText("IMAGE 6 *");
        image6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                image6ActionPerformed(evt);
            }
        });

        shortDescription.setBackground(new java.awt.Color(51, 51, 51));
        shortDescription.setColumns(20);
        shortDescription.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        shortDescription.setForeground(new java.awt.Color(255, 255, 255));
        shortDescription.setLineWrap(true);
        shortDescription.setRows(5);
        shortDescription.setWrapStyleWord(true);
        shortDescription.setAutoscrolls(false);
        shortDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SHORT DECRIPTION *", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        shortDescription.setCaretColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(shortDescription);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\emrec\\OneDrive\\Masaüstü\\airbnb_desktop\\src\\main\\img\\img\\main_logo_1.png")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(advertisementName, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(yesPark)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(noPark))
                                    .addComponent(heatingType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(advertisementType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(image4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(dailyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(350, 350, 350)
                            .addComponent(image5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(image2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(image5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(image4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(advertisementName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(roomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yesPark)
                                    .addComponent(noPark))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(heatingType, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(advertisementType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(dailyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 1220, 730));

        turnHome.setBackground(new java.awt.Color(51, 51, 51));
        turnHome.setForeground(new java.awt.Color(255, 255, 255));
        turnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\emrec\\OneDrive\\Masaüstü\\airbnb_desktop\\src\\main\\img\\img\\back.png")); // NOI18N
        turnHome.setBorder(null);
        turnHome.setBorderPainted(false);
        turnHome.setContentAreaFilled(false);
        turnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        turnHome.setDefaultCapable(false);
        turnHome.setFocusPainted(false);
        turnHome.setRolloverEnabled(false);
        turnHome.setVerifyInputWhenFocusTarget(false);
        turnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(turnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 60, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void advertisementTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertisementTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertisementTypeActionPerformed

    private void roomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNumberActionPerformed

    private void heatingTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heatingTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heatingTypeActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void advertisementNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advertisementNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advertisementNameActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if (dailyPrice.getText().isEmpty() ||shortDescription.getText().isEmpty() || image1.getIcon() == null || image2.getIcon() == null || image3.getIcon() == null || image4.getIcon() == null || image5.getIcon() == null || image6.getIcon() == null) {
            JOptionPane.showMessageDialog(null, "Please Fill All Fields");
        } else {
            HouseFactory houseFactory = new HouseFactory();
            House house = houseFactory.createHouse(advertisementType.getSelectedItem().toString(), files, paths);
            house.setHeating(advertisement.getHouse().getHeating());
            house.setHouseOwnerId(houseOwner.getId());
            house.setId(advertisement.getHouse().getId());
            house.setLocation(advertisement.getHouse().getLocation());
            house.setRoomNumber(advertisement.getHouse().getRoomNumber());
            house.setShortDescription(shortDescription.getText());
            house.update(files, paths);

            advertisement.setActivationPersonnelId(0);
            advertisement.setActivationResult(false);
            advertisement.setAdvertisementName(advertisementName.getText());
            advertisement.setComments(null);
            advertisement.setHouse(house);
            advertisement.setHouseOwnerId(houseOwner.getId());
            advertisement.setId(advertisement.getId());
            String[] price = dailyPrice.getText().split("\\.");
            advertisement.setPrice(Integer.parseInt(price[0]));
            advertisement.update();

            JOptionPane.showMessageDialog(null, "Advertisement updated , Please Wait Personnel Validation");
            this.dispose();
            HomeScreen home = new HomeScreen(houseOwner);
            home.show();
        }
    }//GEN-LAST:event_addActionPerformed

    private void image1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG", "png", "jpeg", "jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);

        if (load == fileChooser.APPROVE_OPTION) {
            files[0] = fileChooser.getSelectedFile();
            paths[0] = files[0].getAbsolutePath();

            ImageIcon imageIcon = new ImageIcon(paths[0]);
            Image img = imageIcon.getImage().getScaledInstance(178, 135, Image.SCALE_SMOOTH);

            image1.setIcon(new ImageIcon(img));

        }
    }//GEN-LAST:event_image1ActionPerformed

    private void image2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image2ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG", "png", "jpeg", "jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);

        if (load == fileChooser.APPROVE_OPTION) {
            files[1] = fileChooser.getSelectedFile();
            paths[1] = files[1].getAbsolutePath();

            ImageIcon imageIcon = new ImageIcon(paths[1]);
            Image img = imageIcon.getImage().getScaledInstance(178, 135, Image.SCALE_SMOOTH);

            image2.setIcon(new ImageIcon(img));

        }
    }//GEN-LAST:event_image2ActionPerformed

    private void image3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image3ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG", "png", "jpeg", "jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);

        if (load == fileChooser.APPROVE_OPTION) {
            files[2] = fileChooser.getSelectedFile();
            paths[2] = files[2].getAbsolutePath();

            ImageIcon imageIcon = new ImageIcon(paths[2]);
            Image img = imageIcon.getImage().getScaledInstance(178, 135, Image.SCALE_SMOOTH);

            image3.setIcon(new ImageIcon(img));

        }
    }//GEN-LAST:event_image3ActionPerformed

    private void image4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image4ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG", "png", "jpeg", "jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);

        if (load == fileChooser.APPROVE_OPTION) {
            files[3] = fileChooser.getSelectedFile();
            paths[3] = files[3].getAbsolutePath();

            ImageIcon imageIcon = new ImageIcon(paths[3]);
            Image img = imageIcon.getImage().getScaledInstance(178, 135, Image.SCALE_SMOOTH);

            image4.setIcon(new ImageIcon(img));

        }
    }//GEN-LAST:event_image4ActionPerformed

    private void image5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image5ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG", "png", "jpeg", "jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);

        if (load == fileChooser.APPROVE_OPTION) {
            files[4] = fileChooser.getSelectedFile();
            paths[4] = files[4].getAbsolutePath();

            ImageIcon imageIcon = new ImageIcon(paths[4]);
            Image img = imageIcon.getImage().getScaledInstance(178, 135, Image.SCALE_SMOOTH);

            image5.setIcon(new ImageIcon(img));

        }
    }//GEN-LAST:event_image5ActionPerformed

    private void image6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_image6ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG", "png", "jpeg", "jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);

        if (load == fileChooser.APPROVE_OPTION) {
            files[5] = fileChooser.getSelectedFile();
            paths[5] = files[5].getAbsolutePath();

            ImageIcon imageIcon = new ImageIcon(paths[5]);
            Image img = imageIcon.getImage().getScaledInstance(178, 135, Image.SCALE_SMOOTH);

            image6.setIcon(new ImageIcon(img));

        }
    }//GEN-LAST:event_image6ActionPerformed

    private void dailyPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailyPriceActionPerformed

    private void turnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeScreen home = new HomeScreen(houseOwner);
        home.show();
    }//GEN-LAST:event_turnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvertisementUpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvertisementUpdateScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JTextField advertisementName;
    private javax.swing.JComboBox<String> advertisementType;
    private javax.swing.JFormattedTextField dailyPrice;
    private javax.swing.ButtonGroup hasPark;
    private javax.swing.JComboBox<String> heatingType;
    private javax.swing.JButton image1;
    private javax.swing.JButton image2;
    private javax.swing.JButton image3;
    private javax.swing.JButton image4;
    private javax.swing.JButton image5;
    private javax.swing.JButton image6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton noPark;
    private javax.swing.JComboBox<String> roomNumber;
    private javax.swing.JTextArea shortDescription;
    private javax.swing.JButton turnHome;
    private javax.swing.JRadioButton yesPark;
    // End of variables declaration//GEN-END:variables
}
